### PR TITLE
VapourSynth Plugin Support

### PR DESCRIPTION
**Pull request by ghost**
Hello. I use VapourSynth R24 on Windows XP, because this is the last version that works on it. Old version, I know, but I love exotic. I would like to ask you upload VapourSynth-XY-VSFilter version 3.1.0.697 as binary. I don't know how to compile the source code, I have never dealt with Visual Studio. I'm not sure that it will run on my computer, and the code will work on XP. Is it possible to build under Linux (for XP)? Or maybe you know who can share a binary file? Sorry, I didn't know where to write, maybe this is not the best place. You can write me an e-mail denislpd at yahoo.com

### CODE REVIEW

**Comment by Cyberbeing** [comment]
@denismn I tried to compile Tsuki's branch for WinXP, does the attached build work?

[vsXP_pull17.zip](https://github.com/Cyberbeing/xy-VSFilter/files/4662591/vsXP_pull17.zip)

**Comment by denismn** [comment]
> does the attached build work?

Unfortunately no. Or am I doing something wrong, the syntax is pretty obscure.
Release Schedule:
5  Mar 2014 3.1.0.682
13 Mar 2014 R23 (No binaries)
30 Apr 2014 3.1.0.697* (your build)
15 Aug 2014 R24 (Last XP Support)
25 Nov 2014 R25
7  Dec 2014 3.0.0.306, 3.1.0.705

Version 3.1.0.697 that you builded was released when there were no 24 release yet. It was tested by the plugin developer on the 23rd release. Perhaps version 3.0.0.306 or 3.1.0.705 will work. By the way, are you sure that you have built a version for VapourSynth (or hybrid) and not for AviSynth only?

Thank you for your work. Although, I no longer use XP and even Windows in general. I am also very saddened by the sad situation with backward compatibility in VapourSynth. And also the incomprehensible syntax of plugins, including the incomprehensible description of building from the source. If it were more understandable (in more detail for beginners) I would build it myself.

By the way, the internal assvapour plugin of version 24 doesn't work (maybe it broken or was not ready yet, I heard something like that). Therefore, I turned to third-party plugins. I think that there is no more sense to test this junk. But if you want, you can build versions 3.0.0.306 and or 3.1.0.705. I will check from a historical point of view.

**Comment by Cyberbeing** [comment]
Did a quick test, and I think I see the problem. The commits you linked added support for Vapoursynth R28. It gets rejected by R24 since the API version changed. That said, you'll have a bad time if you are stuck on that version, since, no plugin updated after January 2015 will function in R24.

Here is a new build which I've verified works with Vapoursynth R24:
[xyvsf_R24_WinXP.zip](https://github.com/Cyberbeing/xy-VSFilter/files/4674572/xyvsf_R24_WinXP.zip)

**Comment by denismn** [comment]
**Error:**

_scrypt.vpy:_
```
import vapoursynth as vs
core = vs.get_core()
video = core.ffms2.Source("input.mkv")
hardsub = core.xyvsf.TextSub(video, "sub.ass")
hardsub.set_output()
```

`vspipe --y4m script.vpy - | ffmpeg -i pipe: -c:v mpeg2video -q:v 1 -aspect 16:9 output.mkv`

```
Script evaluation failed:
Python exception: No attribute with the name xyvsf exists. Did you mistype a plugin namespace?
Traceback (most recent call last):
  File "vapoursynth.pyx", line 1406, in vapoursynth.vpy_evaluateScript (src\cython\vapoursynth.c:218
40)
  File "script.vpy", line 4, in <module>
    hardsub = core.xyvsf.TextSub(video, "sub.ass")
  File "vapoursynth.pyx", line 1036, in vapoursynth.Core.__getattr__ (src\cython\vapoursynth.c:16361
)
vapoursynth.Error: No attribute with the name xyvsf exists. Did you mistype a plugin namespace?
pipe:: Invalid data found when processing input
```

VSFilter.dll and ffms2.dll (v2.20) in C:\Program Files\VapourSynth\plugins32
2010, 2012, 2013, 2015-2019 (27 May 2020) redist installed. Python 3.4.4.

VapourSynth, Python and ffmpeg in PATH:

> HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment
> Path = %SystemRoot%\system32;%SystemRoot%;%SystemRoot%\system32\wbem;C:\Program Files\Python;C:\Program Files\Python\Scripts;C:\Program Files\VapourSynth\core32

However, it works as AviSynth imported plugin https://github.com/Cyberbeing/xy-VSFilter/releases/tag/3.0.0.306

```
import vapoursynth as vs
core = vs.get_core()
core.avs.LoadPlugin('c:/AviSynth/plugins/VSFilter.dll')
video = core.ffms2.Source("input.mkv")
hardsub = core.avs.TextSub(video, "sub.ass")
hardsub.set_output()
```

> I've verified works with Vapoursynth R24

Perhaps you checked in VapourSynth 24 on Windows 7-10, but not XP?
I checked in a virtual machine with XP SP3.

> you'll have a bad time if you are stuck on that version, since no plugin updated after January 2015 will function with R24

2015 is not so bad. All you need is for the plugins to be available for download. For example, the legendary program XviD4PSP 5 has a year of release 2015.

**Comment by Cyberbeing** [comment]
Yes, I tested it on Windows 7 with VapourSynth 24 + Python 3.4.10, since I no longer have a WinXP install. What error do you get with the VSFilter.dll in xyvsf_R24_WinXP.zip when you try to load it manually as a Vapoursynth Plugin using `core.std.LoadPlugin` ?

**Comment by denismn** [comment]
```
Script evaluation failed:
Python exception: Failed to load c:/VSFilter.dll
Traceback (most recent call last):
  File "vapoursynth.pyx", line 1406, in vapoursynth.vpy_evaluateScript (src\cytho\vapoursynth.c:21840)
  File "script3.vpy", line 3, in <module> core.std.LoadPlugin('c:/VSFilter.dll')
  File "vapoursynth.pyx", line 1307, in vapoursynth.Function.__call__ (src\cytho\vapoursynth.c:20422)
vapoursynth.Error: Failed to load c:/VSFilter.dll
pipe:: Invalid data found when processing input
```

The same error as if the plugin file name was incorrect, by the way. But it is correct. ffms2 is loaded manually.

And if connect avisynth'vsfilter.dll through core.std.LoadPlugin (just for fun, I mixed them up once), then it says "No entry point found".

> I tested it on Windows 7

A lot of things don't work on XP. In particular, a special build of ffmpeg libraries is needed.

**Comment by Cyberbeing** [comment]
[xyvsf_R24_WinXP_Dynamic.zip](https://github.com/Cyberbeing/xy-VSFilter/files/4694084/xyvsf_R24_WinXP_Dynamic.zip)

Last attempt. If this doesn't work, I'm out of ideas. The above build is no longer static, so it will require https://aka.ms/vs/16/release/vc_redist.x86.exe be installed.

**Comment by denismn** [comment]
Unfortunately, the same error. After I removed 2019 redistr, an error occurred about failure to load mfc140.dll. This means that the plugin is trying to load, but cannot.

In any case, thank you for your time. It's still possible burn subtitles through the avisynth plugin.

**Comment by Cyberbeing** [comment]
That's unfortunate, makes me wonder if the VS2017 WinXP Targeting Toolset 141_xp installed via VS2019 isn't WinXP compatible when using ATL or MFC.  Either that, or there is something about xy-VSFilter Vaporsynth plugin code itself which doesn't like WinXP. 

I'm going to close this Pull Request, since the plugin for whatever reason doesn't seem to be WinXP compatible when compiled for WinXP. If anyone is looking for VapourSynth Plugin builds for Win7 x64 or newer, https://github.com/HomeOfVapourSynthEvolution/xy-VSFilter/releases is probably the best source.

**Comment by Cyberbeing** [comment]
Re-opening this, since now that even Win7 ESU support ended last month, it is likely time to stop caring about continued support of Windows XP and consider adding VapourSynth Plugin Support.

**Comment by Masaiki** [comment]
a widely used fork with vapoursynth support is [here](https://github.com/HomeOfVapourSynthEvolution/xy-VSFilter)

**Comment by Cyberbeing** [comment]
@Masaiki Would you like to make a new pull request for VapourSynth support which is squashed and rebased to our codebase? I assume ghost is no longer around to add new commits or make changes.

**Pull request closed without merging**
