### PR TITLE
Library update (again)

### PR DESCRIPTION
**Pull request by BrunoReX**
Tested with VS2013, both Release and Debug builds compile and work.
The extra Boost dirs (align, core, and predef) were needed for compilation.

### CODE REVIEW

**Comment by amayra** [comment]
i think you should update it again 
Update UnRAR to v5.2.6
Update Boost to 1.57.0 or 1.58.0 beta1

**Comment by kasper93** [comment]
@amayra: And what is the point? This project is basically dead, updating libs will not bring live to it and may result in regression.

**Comment by Cyberbeing** [comment]
Updating the libraries occasionally is something which should be done anyway, even if the project is in maintenance mode. Though at this point I'd rather wait until we need to add Visual Studio 2015 build support, and do both at the same time.

**Comment by Cyberbeing** [comment]
@amayra 
Next week, I'll likely release a new xy-VSFilter & XySubFilter build for some parsing improvements related to MKV 'cue relative position' seeking performance (now supported by LAV Filters nightly builds). At the same time, I'll update UnRAR to 5.6.7, Boost to 1.57.0, and log4cplus to 1.0.4.3.

**Comment by mibby** [comment]
@Cyberbeing Any news on the new build? Nearing the end of the month.

**Comment by Cyberbeing** [comment]
I've been busy these past couple weeks, so I'm now unsure when I'll end up pushing out a release. The main delay at this point is finding time to do some through regression testing. For anyone interested, you can try out the linked XySubFilter test build below:

https://drive.bitcasa.com/send/rPJfzK2mXrkUM7caspzidkMLZ6DbLkpuNRFMz3SDyRwc

**Comment by mibby** [comment]
@Cyberbeing Thanks for the build. Unfortunately I ran into a case of madVR crashing at a certain location with subtitles on, with build 3.1.0.741. Downgrading to 3.1.0.705, playback does not crash.

I'm not sure how much it will help with debugging what the problem may be, but here is the crash log and madvr debug log.

Debug log - https://www.dropbox.com/s/hi8yiom7xcwayc3/madVR%20-%20log.txt?dl=0
Crash report - https://www.dropbox.com/s/zmh0eoshhfpesxp/madVR%20-%20crash%20report.txt?dl=0

I believe the crash occurs here in the madvr debug log.
```
00000158.322 Subtitle CQueue::LockItem(self: 0000004CE91AA7B0) -> - (DontLockItems)
00000158.325 Subtitle CQueue::LockItem(self: 0000004CE91AA7B0, id: 3);
``` 

In the meantime, I'll be downgrading back to the public release build 3.1.0.705.

**Comment by Cyberbeing** [comment]
XySubFilter test build 3.1.0.741 v2:
https://drive.bitcasa.com/send/v4JD64-qOf3rEX5JPCyLahV7obSIDSBEp7TdlYNrN4iI

That build should fix the crash which was occurring with the video in your log at 9:05 during \clip tag parsing. Otherwise identical to the v1 build.

**Comment by mibby** [comment]
Confirmed fixed, thanks. No longer crashing at that spot. I'll let you know if I run into any other issues with 3.1.0.741.

**Comment by amayra** [comment]
this build crash in almost all video (DIVX mkv) file i have i well upload simple later

**Pull request closed without merging**
